# Generated by Django 2.1.5 on 2020-01-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=20000, max_length=225),
            preserve_default=False,
        ),
    ]
