# Generated by Django 2.1.5 on 2020-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200111_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
